language: java
jdk:
  -openjdk8
  
addons:
  sonarcloud:
    organization: jdgifgiegifugrsigskjsgeirgsrhjrskjdhfsihusugeuhdsskhyds
    token: 98d77c8386da8eab320321e4eecc0758d3864218

script: 
  - ant build
  - sonar-scanner
